CONFIRM = '\N{WHITE HEAVY CHECK MARK}'
CANCEL = '\N{NO ENTRY SIGN}'

PASS = '\N{WHITE HEAVY CHECK MARK}'
FAIL = '\N{NO ENTRY SIGN}'
DELETE = '\N{WASTEBASKET}'
REOPEN = '\N{BALLOT BOX WITH BALLOT}'

VOTE_FOR = '\N{THUMBS UP SIGN}'
VOTE_AGAINST = '\N{THUMBS DOWN SIGN}'
VOTE_ABSTAIN = '\N{SHRUG}'

VOTES = {VOTE_FOR, VOTE_AGAINST, VOTE_ABSTAIN}

REVEAL = '\N{EYE}'

SUCCESS = '\N{THUMBS UP SIGN}'
FAILURE = '\N{THUMBS DOWN SIGN}'
