CONFIRM = '\N{WHITE HEAVY CHECK MARK}'
CANCEL = '\N{NO ENTRY SIGN}'

PASS = '\N{WHITE HEAVY CHECK MARK}'
FAIL = '\N{NO ENTRY SIGN}'
DELETE = '\N{WASTEBASKET}'

VOTE_FOR = '\N{THUMBS UP SIGN}'
VOTE_AGAINST = '\N{THUMBS DOWN SIGN}'
VOTE_ABSTAIN = '\N{SHRUG}'

SUCCESS = '\N{THUMBS UP SIGN}'
FAILURE = '\N{THUMBS DOWN SIGN}'
