CONFIRM = '\N{WHITE HEAVY CHECK MARK}'
CANCEL = '\N{NO ENTRY SIGN}'

VOTE_FOR = '\N{THUMBS UP SIGN}'
VOTE_AGAINST = '\N{THUMBS DOWN SIGN}'
VOTE_ABSTAIN = '\N{SHRUG}'

SUCCESS = '\N{THUMBS UP SIGN}'
FAILURE = '\N{THUMBS DOWN SIGN}'
